### ISSUE TITLE
Code is unable to save

### ISSUE THREAD

**Issue by Gvashi** [microsoft/MCW-Modern-cloud-apps#38]
Exercide 5 :->Task 3:->subtask2:->step 35
That code is unable to save

**Comment by timahenning** [comment]
Thank you for reporting this issue.  Please take a moment to review the help and support guidance.  https://microsoftcloudworkshop.com/  We will review your issue soon.

Can you provide a little more issue detail?  'That code is enable to save' indicates the code is working.  Did you mean to say is 'unable'?

Tim

**Comment by Gvashi** [comment]
Hi
M sorry for that but it's unable.json file is unable to save.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by crpietschmann** [comment]
This issue has been resolved.

The issue was caused by the old "Execute Stored Procedure" action no longer being available in the Logic App Designer. The "Execute Stored Procedure (V2)" action is now the only option for that Action, and the name of the action in the JSON is different as it contains a "(V2)" moniker that needed to be updated in the JSON changes for the HOL.
