### ISSUE TITLE
No Data in Database.  No Products.  Connection String good.

### ISSUE THREAD

**Issue by mapoitras** [microsoft/MCW-Modern-cloud-apps#45]
When I complete the steps, there is no data in the Database.  So no products.  I have verified the connection strings with App Service Diagnostics.  I know its right.  I tried twice and got same result both times.  Is there supposed to be a load script of some sort?

**Comment by DawnmarieDesJardins** [comment]
@mapoitras @timahenning 
Thanks Marc-Andre - we have an update ready to QC/merge that may fix this issue.  Please stay tuned.
Tim - please verify, after the PR is merged, and resolve as needed.

**Comment by crpietschmann** [comment]
I have run through the MCW and everything had worked as expected for me. That said, the latest update to the MCW, that should be merged soon, includes changes that migrate the application code to ASP.NET Core and .NET Core. In order to perform the update I needed to verify that everything worked with the new code too.

The app uses EF to automatically seed that database with data the first time the app connects. If you still have this issue after the update merge, please post more detail here so we can work to troubleshoot things.

Thanks!

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved with recent November update - PR #40 merge.
@mapoitras please let us know if you are still having trouble.
